### ISSUE TITLE
Käyttäjätunnusten teko

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/bultti#10]
Toimija
HSL pääkäyttäjä

Esiehto
Tunnuksia pystyy tekemään järjestelmässä, tunnukset on pyydetty tehtäväksi

Lopputulos
Toimivat tunnukset käyttäjällä tarkoituksenmukaisilla käyttöoikeuksilla

Käyttötiheys
Harvoin

1
HSL:n pääkäyttäjälle tulee pyyntö tehdä uudet tunnukset. Käyttäjä kirjautuu järjestelmään ja menee hallin-taikkunaan. Hallintaikkunalla tämä valitsee käyttäjätunnusten hallinnan.
2
Järjestelmä tunnistaa käyttäjän pääkäyttäjäksi ja että tällä on oikeus hallinnoida käyttäjätunnuksia. Järjes-telmä siirtää käyttäjän käyttäjätunnusten hallintaan. Valittavissa on uusien tunnusten luominen ja vanho-jen hallinta (aktivointi / deaktivointi, salasanan vaihto).
3
Käyttäjä valitsee "luo uusi" ja antaa tiedot: nimi, organisaatio, sähköpostiosoite, käyttöoikeudet, salasana ja tila. Organisaatio, käyttöoikeudet ja tila ovat alasvetovalikkona, joten niihin voi syöttää vain ennalta määrättyjä tietoja.
4
Järjestelmässä tarjoaa organisaatiokenttään valinnaksi kaikki konsernit, jotka järjestelmän taulusta "kon-sernit". Taulussa on Joren dbo_jr_konserni taulun tietojen lisäksi yhtenä rivinä HSL. Käyttöoikeuksina on valittavina a)pääkäyttäjä, b)HSL muokkaaja ylempi, c)HSL muokkaaja alempi, d) HSL selaaja e) liikennöitsijä muokkaaja, f) liikennöitsijä selaaja, g) muu selaaja. Tilana on aktiivinen / passiivinen. Passiiviset tunnukset eivät toimi.
5
Käyttäjä tallentaa tunnukset, kun tiedot on annettu.
6
Järjestelmä tallentaa tunnukset ja ne ovat heti käytettävissä.
7
Käyttäjä siirtyy takaisin etusivulle.
8

Variaatiot
V7
Käyttäjä muokkaa vanhoja tunnuksia. Käyttäjä valitsee listasta muokattavat tunnukset, tekee haluamansa muutokset (salasanan vaihto tai tilan muutos) ja tallentaa. Järjestelmä tallentaa tiedot vanhojen päälle.
V8
Käyttäjä on unohtanut salasanan ja aktivoi järjestelmän etusivulla salasanan palautuksen. Käyttäjän aktivoi salasanan palautus antamalla oma käyttäjätunnuksen tai sähköpostiosoitteen. Salasanan palautuksen yh-teydessä on tarkistettava, että palauttava taho on varmasti ihminen. Esimerkiksi voidaan käyttää kuvatar-kistusta, jossa kuva ei ole koneellisesti luettavissa. Kun palvelu palauttaa käyttäjän salasanan, on sähkö-postiin toimitettavan palautussalasanan oltava satunnainen ja kertakäyttöinen. Palautussalasanan voimas-saoloajan tulee olla HSL:n määriteltävissä. Palautussalasanan saa lähettää ainoastaan käyttäjän tiedoissa olevaan sähköpostiin. Salasanan palautus -sähköpostissa on oltava linkki salasanan palautukseen, johon kirjaudutaan palautetulla kertakäyttösalasanalla. Salasanan palautus -sähköpostissa on lisäksi oltava linkki, jota klikkaamalla käyttäjä pystyy suoraan ilmoittamaan mahdollisesta salasanan palautus väärinkäytökses-tä. Vanhan salasanan on toimittava käyttäjän hyväksymään palautukseen asti. Salasanan palautus katso-taan hyväksytyksi, kun käyttäjä on saamallaan kertakäyttöisellä salasanalla tehnyt itselleen uuden salasa-nan. Käyttäjän tiedoissa olevaan sähköpostiin tulee ilmoittaa salasanan palautuksesta myös hyväksytyn salasanan palautuksen jälkeen.
V4
Käyttäjä, jolla ei ole käyttöoikeuksia, yrittää päästä muokkaamaan tietoja. Järjestelmässä ei ole valittava osio näkyvillä tai se ilmoittaa, että käyttöoikeudet eivät riitä.

Poikkeukset
P1
Tekninen vika. Järjestelmä ilmoittaa keskeytymisestä.
P2
Käyttäjä yrittää syöttää liian heikon salasanan. Järjestelmä ei sitä hyväksy ja ohjeistaa antamaan oikeanlai-sen salasanan.

**Comment by danieldunderfelt** [comment]
Onko toive että käyttäjille jaetaan oikeuksia sähköpostidomainin perusteella samalla tavoin kun Reittilokissa, tai tuleeko kaikille käyttäjille antaa käyttöoikeudet erikseen HSL ID ylläpito-näkymän kautta?

**Comment by samijuhani** [comment]
Annetaan erikseen ylläpidon kautta.
