### ISSUE TITLE
Start using ESLint

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#114]
Task done in here: https://github.com/HSLdevcom/bultti/issues/188

TSLint was deprecated by ESLint so I guess we should start using ESLint here

Add rules:
curly: { all }
https://eslint.org/docs/rules/curly

**Comment by danieldunderfelt** [comment]
Yes! Been on the bottom of my todo list for a while...

But let's not have any weird rules, a good starting place is the Create React App rules which the UI uses.
