### ISSUE TITLE
Ennakkotarkastuksen tarkemmat ominaisuudet

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/bultti#12]
Tähän määrittelyä mitä tarkastus sisältää. Tiedot mitä Kirsi syöttää (poikkeavat mitä sopimuksista ei suoraan ole tietokannassa).

**Comment by samijuhani** [comment]
[Bultti demo 0.2 Arkkitehtuuri.pptx](https://github.com/HSLdevcom/bultti/files/3320315/Bultti.demo.0.2.Arkkitehtuuri.pptx)

**Comment by KirsiGupta** [comment]
Päästöluokka tarkastus (keskusta-alue ja muu alue), kalustotyyppi tarkastus, keski-ikä, liikennöitsijän lähtöketjuista puuttuvat lähdöt, runkolinjaväritys, elpymisajat,
