### ISSUE TITLE
Luokkakaaviot ja raportit

### ISSUE THREAD

**Issue by TiinaKoi** [HSLdevcom/bultti#14]

**Comment by TiinaKoi** [comment]
Kaaviot ja raportit

**Comment by TiinaKoi** [comment]
[Luokkakaaviot raportit ja tarvittavat Joret.xlsx](https://github.com/HSLdevcom/bultti/files/3579036/Luokkakaaviot.raportit.ja.tarvittavat.Joret.xlsx)

**Comment by danieldunderfelt** [comment]
Moved to wiki: https://github.com/HSLdevcom/bultti/wiki/Class-hierarchy-and-JORE-requirements-excel
