### ISSUE TITLE
Remove create inspection buttons from pre/post inspection pages

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#167]
FE PR: https://github.com/HSLdevcom/bultti-ui/pull/44

These buttons are not working currently (as you would expect):

![luo_ennakkotarkastus](https://user-images.githubusercontent.com/1419296/105808427-61863400-5fb0-11eb-9b51-326ea7120b29.png)

But as I can't find any way of how they should work in other way than the header's "create new inspection button" -> remove those buttons completely as they don't serve a purpose

**Comment by SuviRossi** [comment]
This is related to #45 and comes after that. Any way to link here? @Divinare 

There is no data for Preinspections as this has been done manually. 

After #45 data is shown here and at that point, past CTA -buttons should not be visible...?
