### ISSUE TITLE
Sort reports in a specific order

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#172]
TODO: **document here a list of the wanted raport's order**. Note: that raports are different in pre/post inspections. **Please make pre/post raport's ordering as close each other as possible** so that it's easier to compare them in UI, in documentation etc.

Current pre inspection raports:
Liikennöitsijän omat linjasivurikkeet
Siirtoajot
Lähtöketjut
Linjasivurikkeet
Päästöluokkien suoritteet
Runkolinjaväritysrikkeet
Kalustotyyppirikkeet
Suoritevaatimukset
Ylimääräiset lähdöt
Puuttuvat lähdöt
Puuttuva kalusto
Liikennöitsijän siirtoajot
Kielletyt yli-ikäisyysrikkeet
Kohteiden suoritteet ja keski-iät
Seurattavat lähdöt

Current post inspection raports:
Toteutuneet suoritevaatimukset
Kohteiden toteutuneet suoritteet ja keski-iät
Myöhästyneet lähdöt
Päästöluokkien suoritteet
Kielletyt yli-ikäisyysrikkeet
Runkolinjaväritysrikkeet
Kalustotyyppirikkeet
Ajantasauspysäkkien laiminlyönnit
Linjasivurikkeet
Toteutumattomat lähdöt

How pre inspection raports should be listed:
- TODO, fill

How post inspection raports should be listed:
- TODO, fill

**Comment by KirsiGupta** [comment]
How pre inspection raports should be listed:

Puuttuva kalusto
Ylimääräiset lähdöt 
Puuttuvat lähdöt
Liikennöitsijän omat linjasivurikkeet
Linjasivurikkeet (HSL+liikennöitsijä) 
Kalustotyyppirikkeet
Runkolinjaväritysrikkeet 
Kielletyt yli-ikäisyysrikkeet 
Kohteiden suoritteet ja keski-iät 
Suoritevaatimukset = Päästöluokka laskelma 
Päästöluokkien suoritteet kohteittain (liikennöitsijän suunnitellut?)  (yhteensä km myös) 
Liikennöitsijän siirtoajot
Siirtoajot 
Seurattavat lähdöt
Lähtöketjut



How post inspection raports should be listed:

Kalustotyyppirikkeet 
Runkolinjaväritysrikkeet
Kielletyt yli-ikäisyysrikkeet
Kohteiden toteutuneet suoritteet ja keski-iät
Toteutuneet suoritevaatimukset = Toteutunut päästöluokka laskelma
Päästöluokkien suoritteet kohteittain (yhteensä km myös)
Linjasivurikkeet
Myöhästyneet lähdöt
Ajantasauspysäkkien laiminlyönnit
Toteutumattomat lähdöt
