### ISSUE TITLE
Data loading and saving improvements for inspections

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#194]
In an ideal solution, reports that have been preloaded can be used straight away for the next steps so that they don't need to be recalculated.

To accomplish this, the data saving step of pre-inspections is moved from before production to between draft and review. Also, the departures are created in a worker task, in line with how ObservedDepartures are created.

**Comment by danieldunderfelt** [comment]
I'm not sure if there is a time between making all inputs in the Inspection editor and the user viewing the reports where a preload can happen, but improvements can definitely be made:

- Collect pre-inspection departures in a worker server task (already done like this for post-inspections). Would result in the departures being available in Redis, now they are only cached in memory.
- Departure collection triggers when the first report is opened, but subsequent reports should detect that it is already in progress and wait for the same task to complete.

**Comment by danieldunderfelt** [comment]
Server PR: #225 

UI PR: HSLdevcom/bultti-ui#57
