### ISSUE TITLE
Minor bug fixes

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#256]
Fixes to be done:
- Fix downloading "Päästöluokkien suoritteet excel raport"
- Fix downloading "Ajantasauspysäkkien laiminlyönnit"
- Fix downloading "Myöhästyneet lähdöt"
- "Ylimääräiset lähdöt" displayed timestamps are broken
- Notification of "tarkastus on hyväksyttävänä" not being delivered via email
- Raport page: add information of what is the season that the raport belongs to
- Inspection status subscription fix
- Dirty form detection and navigation block problems: contract edit, inspection config

**Comment by MinnaEmilia** [comment]
Omat tiketit luotu korjauksista. Suljetaan tämä tiketti.
