### ISSUE TITLE
Inspection date editing fixes

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#291]
* PostInspection: 
** Check that editing of the "tarkastusjakso" is disabled when the inspection is not editable.
** Jälkitarkastuksesta otetaan pois tuotantojakso.
* PreInspection: Currently tuotantojakso has no minDate - I was able to put endDate before season start and save, then it changed as season startDate + 1. Just add minStartDate which is the season's first week's sunday

**Comment by MinnaEmilia** [comment]
@Divinare and @danieldunderfelt can you check whether pre inspection really has the described challenge.
