### ISSUE TITLE
Ennakkotarkastus: prosenttiosuuksien päivittyminen (0,5d)

### ISSUE THREAD

**Issue by MinnaEmilia** [HSLdevcom/bultti#318]
BE PR: https://github.com/HSLdevcom/bultti/pull/323

Käyttäjä haluan, että ennakkotarkastuksessa suoritevaatimuksen prosenttiosuutta muokatessa tai ajoneuvoja poistaessa kokonaisprosentti on 100%. Tällä hetkellä tietojen muokkauksen myötä muut rivit eivät päivity ja kokonaisprosentti ei ole sen takia 100%.

Myös muissa taulukoissa ongelmaa %-osuuksien päivityksessä. Tarkastetaan tämän tiketin yhteydessä kaikkien %-osuuksien päivittyminen.

**Comment by danieldunderfelt** [comment]
How it should work:

- Editing a percentage quota in the equipment table of an execution requirement should be reflected in the total sum for the column. This was broken.
- Adding or removing equipment should recalculate all other quotas to keep the percentage the same. This worked as far as I could tell.
