### ISSUE TITLE
tuhat erotin kaikkiin lukuihin ja %-lukuihin pilkut oikein (0,8))

### ISSUE THREAD

**Issue by MinnaEmilia** [HSLdevcom/bultti#322]
Osassa %-osuuksissa on tuhaterotin, vaikka pitäisi olla pilkku.

Osassa metriosuuksissa ei ole tuhaterotinta. Tuhat erotin halutaan kaikkiin lukuihin.

**Comment by danieldunderfelt** [comment]
Virhe johtunee tästä:

```
export function getThousandSeparatedNumber(input: Big | number | string): string {
  return Big(input).toNumber().toLocaleString().replace(',', ' ')
}
```

Tiedostossa `util/formatNumber.ts`. Jos luvut ei näytä virheelliseltä, se johtuu siitä että koneella on eri lokaali missä ne näkyy oikein.
