### ISSUE TITLE
Kirjautuminen

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/bultti#8]
Toimija
Kaikki käyttäjät

Esiehto
Käyttäjällä on tunnukset

Lopputulos
Käyttäjä pääsee järjestelmään

Käyttötiheys
Kuukausittain

1
Käyttäjälle näytetään kirjautumissivu.
2
Käyttäjä kirjautuu järjestelmään ja siirtyy etusivulle.
3
Kirjautumisen jälkeen järjestelmä hakee kirjautuneen käyttäjän tiedot ja siirtää käyttäjän automaattisesti etusivulle. Järjestelmä tunnistaa käyttäjän käyttöoikeudet järjestelmässä ja tarjoaa vain sellaisia toiminto-ja, jotka tälle on sallittuja.

Variaatiot
V5
Käyttäjä ei jatka käyttötapausta loppuun vaan sulkee selaimen. Käyttötapaus päättyy.
V6
Käyttäjä syöttää väärän salasanan tai käyttäjätunnuksen. Järjestelmä ilmoittaa, kuinka toimia.

Poikkeukset
P7
Käyttäjä pyytää uutta salasanaa. Järjestelmä ilmoittaa, kuinka toimia.
P8
Tekninen vika. Järjestelmä ilmoittaa käyttökatkosta.

**Comment by danieldunderfelt** [comment]
Tämä on periaatteessa jo toteutettu, vaikka toimintoja ei vielä ole. Mutta kirjautuminen toimii!
