### ISSUE TITLE
Add inspection date ranges from admin view

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#91]
FE PR: https://github.com/HSLdevcom/bultti-ui/pull/14
BE PR: https://github.com/HSLdevcom/bultti/pull/94

--- Bultti BE ---

Create a new folder: common/inspectionDate
Create a new entity: common/inspectionDate/InspectionDateEntity

In folder common/inspectionDate/

InspectionDateEntity.ts

id, type: ID
startDate:, type: 'date'
startEnd:, type: 'date'

InspectionDateResolver.ts

Add methods:
- createInspectionDate (remember to validate)

--- Bultti FE ---

New view: InspectionDateView.tsx

- Show list of current inspection dates
- In the end of the list, add a button [Lisää uusi tarkastelujakso]

Alkupäivä         Loppupäivä
dd.mm.yyyy input  dd.mm.yyyy input

(remember validations, cant overlap with existing ones etc!)

[Tallenna]

PostInspection view: 

Change "Tarkastusjakso" selection as a dropdown instead of having two calendars

validations:
- can only select ones that have ended one month ago
- can't select a date that already has a post inspection (?)

**Comment by danieldunderfelt** [comment]
Validations:

- can only select ones that have ended one ~month~ day ago
- in kalustovikasanktiointi we can use a month
- can have many post-inspections for the same dates
- can only CREATE InspectionDates which don't already exist and don't overlap with existing ones
