### ISSUE TITLE
InspectionForms: switch date fields into a dropdown

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/bultti#95]
FE PR: https://github.com/HSLdevcom/bultti-ui/pull/40
BE PR: https://github.com/HSLdevcom/bultti/pull/169

Set min/max date with: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

- PreInspectionForm
    - generate options to be selected from (dropdown selection sets inspectionStartDate and inspectionEndDate)

- PostInspectionForm
   - get startDate & endDate from InspectionDates  (dropdown selection sets inspectionStartDate and inspectionEndDate)
    - can only select ones that have ended one month ago

Also remove inspection.minStartDate

**Comment by danieldunderfelt** [comment]
Please leave `inspection.inspectionStartDate` and `inspection.inspectionEndDate` and write the dates from the InspectionDate to these fields on the Inspection entity when connected. These properties are in heavy use and it's convenient to not always have to fetch the InspectionDate entity.
